name: flutter_training
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  build_runner: ^2.4.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  yumemi_weather:
    git:
      url: https://github.com/yumemi-inc/flutter-training-template.git
      ref: main
      path: packages/yumemi_weather

dev_dependencies:
  flutter_test:
    sdk: flutter
  blendthink_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
